run_name: WikiDiverse
seed: 43
pretrained_model: 'openai/clip-vit-base-patch32'
lr: 1e-5


data:
  num_entity: 132460
  kb_img_folder: /content/WikiDiverse/kb_image
  mention_img_folder: /content/WikiDiverse/mention_image
  qid2id: /content/WikiDiverse/qid2id.json
  entity: /content/WikiDiverse/kb_entity.json
  train_file: /content/WikiDiverse/wiki_diverse_train.json
  dev_file: /content/WikiDiverse/wiki_diverse_dev.json
  test_file: /content/WikiDiverse/wiki_diverse_test.json

  batch_size: 16
  num_workers: 4
  text_max_length: 40

  eval_chunk_size: 50
  eval_batch_size: 4
  embed_update_batch_size: 8


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96
  dv: 96
  dt: 512
  TGLU_hidden_dim: 96
  IDLU_hidden_dim: 96
  CMFU_hidden_dim: 96


trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  log_every_n_steps: 30
